#!/usr/bin/env node
/**
 * Embeds the web console sources (src/web/frontend/*) into src/web/ui-bundle.ts
 * so the installed CLI serves the page without reading files. Runs before
 * build-cli, which bundles ui-bundle.ts into dist. Page assembly itself lives
 * in src/web/assemble-page.ts; this script only collects the files and checks
 * that they assemble.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { inlinePage } from "../src/web/assemble-page.ts";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const frontendDir = path.join(root, "src/web/frontend");

const files = Object.fromEntries(
  fs.readdirSync(frontendDir)
    .filter((name) => /\.(html|css|js)$/.test(name))
    .sort()
    .map((name) => [name, fs.readFileSync(path.join(frontendDir, name), "utf8")]),
);

// Fail the build, not the first page load, when index.html references a missing file.
inlinePage(files);

const bundleTs = `// Generated by scripts/build-web.mjs — do not edit manually.
// Sources: src/web/frontend/ (index.html and the styles/scripts it references).

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { inlinePage, inlineScripts, personalize, type FrontendFiles } from "./assemble-page.ts";

const EMBEDDED: FrontendFiles = ${JSON.stringify(files, null, 2)};

/** A source checkout serves the live files, so editing the frontend needs no rebuild. */
function frontendFiles(): FrontendFiles {
  const dir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../src/web/frontend");
  if (!fs.existsSync(path.join(dir, "index.html"))) return EMBEDDED;
  return Object.fromEntries(
    fs.readdirSync(dir)
      .filter((name) => /\\.(html|css|js)$/.test(name))
      .map((name) => [name, fs.readFileSync(path.join(dir, name), "utf8")]),
  );
}

export function getWebUiHtml(options: { version: string; defaultSessionId?: string }): string {
  return personalize(inlinePage(frontendFiles()), options);
}

export function getClientScript(): string {
  return inlineScripts(frontendFiles());
}
`;

fs.writeFileSync(path.join(root, "src/web/ui-bundle.ts"), bundleTs, "utf8");
console.log("build-web: wrote src/web/ui-bundle.ts from src/web/frontend/");
