#!/usr/bin/env node
/**
 * Ahead-of-time CLI bundles for production install.
 * Bundles workspace TypeScript only; leaves package dependencies external so
 * Node can resolve CJS deps (ink/react/etc.) without "Dynamic require" failures.
 * Code-splitting keeps `xio --version` from loading session/Ink chunks.
 */
import * as esbuild from "esbuild";
import { mkdir, writeFile, rm } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dist = path.join(root, "dist");
await rm(dist, { recursive: true, force: true });
await mkdir(dist, { recursive: true });

const common = {
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node22",
  sourcemap: true,
  splitting: true,
  // Externalize npm deps; bundle only repo sources (src/ + extensions/).
  packages: "external",
  // Resolve .ts extensions used in local imports.
  resolveExtensions: [".ts", ".tsx", ".js", ".mjs", ".json"],
  loader: { ".ts": "ts", ".tsx": "tsx" },
  banner: {
    js: "// Generated by scripts/build-cli.mjs — do not edit.",
  },
  logLevel: "info",
};

await esbuild.build({
  ...common,
  entryPoints: {
    xio: path.join(root, "src/cli/entry.ts"),
    "xio-improve": path.join(root, "src/cli/improve-entry.ts"),
  },
  outdir: dist,
  entryNames: "[name]",
  chunkNames: "chunks/[name]-[hash]",
});

await writeFile(path.join(dist, ".build-stamp"), `${new Date().toISOString()}\n`, "utf8");
console.log("build-cli: wrote dist/xio.js and dist/xio-improve.js (ESM split, packages external)");
