#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const frontendDir = path.join(root, "src/web/frontend");
const distWebDir = path.join(root, "dist/web");

if (!fs.existsSync(distWebDir)) {
  fs.mkdirSync(distWebDir, { recursive: true });
}

const styles = fs.readFileSync(path.join(frontendDir, "styles.css"), "utf8");
const script = fs.readFileSync(path.join(frontendDir, "app.js"), "utf8");
const markup = fs.readFileSync(path.join(frontendDir, "index.html"), "utf8");

// Extract the body content from index.html (excluding header and script tags)
const bodyMatch = markup.match(/<body>([\s\S]*?)<script src="app\.js"><\/script>\s*<\/body>/i);
const bodyContent = bodyMatch ? bodyMatch[1].trim() : markup;

// Generate dist/web/index.html with inlined css and js for zero-network local delivery
const compiledHtml = `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>XioCode 控制台</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
  <style>
${styles}
  </style>
</head>
<body>
${bodyContent}
  <script>
${script}
  </script>
</body>
</html>
`;

fs.writeFileSync(path.join(distWebDir, "index.html"), compiledHtml, "utf8");

// Also generate src/web/ui-bundle.ts so runtime does not require file IO if running from dist
const bundleTs = `// Generated by scripts/build-web.mjs — do not edit manually.
// Source files located in src/web/frontend/ (styles.css, app.js, index.html)

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const COMPILED_TEMPLATE = ${JSON.stringify(compiledHtml)};

export function getWebUiHtml(options: { version: string; defaultSessionId?: string }): string {
  // If running in development with src/web/frontend available, hot-read for immediate dev reload
  try {
    const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
    const frontendDir = path.join(root, "src/web/frontend");
    if (fs.existsSync(path.join(frontendDir, "index.html"))) {
      const devStyles = fs.readFileSync(path.join(frontendDir, "styles.css"), "utf8");
      const devScript = fs.readFileSync(path.join(frontendDir, "app.js"), "utf8")
        .replace(/__VERSION__/g, options.version)
        .replace(/const DEFAULT_SESSION_ID = "";/, \`const DEFAULT_SESSION_ID = "\${options.defaultSessionId || ""}";\`);
      const devMarkup = fs.readFileSync(path.join(frontendDir, "index.html"), "utf8");
      const match = devMarkup.match(/<body>([\\s\\S]*?)<script src="app\\.js"><\\/script>\\s*<\\/body>/i);
      const devBody = match && match[1] ? match[1].trim() : devMarkup;
      return \`<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>XioCode 控制台</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
  <style>
\${devStyles}
  </style>
</head>
<body>
\${devBody}
  <script>
\${devScript}
  </script>
</body>
</html>\`;
    }
  } catch {
    // Fallback to embedded template
  }
  return COMPILED_TEMPLATE
    .replace(/__VERSION__/g, options.version)
    .replace(/const DEFAULT_SESSION_ID = "";/, \`const DEFAULT_SESSION_ID = "\${options.defaultSessionId || ""}";\`);
}

export function getClientScript(): string {
  try {
    const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
    const appJs = path.join(root, "src/web/frontend/app.js");
    if (fs.existsSync(appJs)) {
      return fs.readFileSync(appJs, "utf8");
    }
  } catch {}
  return ${JSON.stringify(script)};
}
`;

fs.writeFileSync(path.join(root, "src/web/ui-bundle.ts"), bundleTs, "utf8");
console.log("build-web: wrote dist/web/index.html and src/web/ui-bundle.ts from src/web/frontend/");
