/**
 * XioCode web console page. Sources live in src/web/frontend/; the embedded
 * copy in ui-bundle.ts is generated by scripts/build-web.mjs.
 */

import { getWebUiHtml, getClientScript } from "./ui-bundle.ts";
import { personalize, type PageOptions } from "./assemble-page.ts";

export function renderWebUiHtml(options: PageOptions): string {
  return getWebUiHtml(options);
}

export function renderUiScript(options?: Omit<PageOptions, "version">): string {
  return personalize(getClientScript(), { version: "", ...options });
}
