/**
 * XioCode web console page. Sources live in src/web/frontend/; the embedded
 * copy in ui-bundle.ts is generated by scripts/build-web.mjs.
 */

import { getWebUiHtml, getClientScript } from "./ui-bundle.ts";
import { personalize } from "./assemble-page.ts";

export function renderWebUiHtml(options: { version: string; defaultSessionId?: string }): string {
  return getWebUiHtml(options);
}

export function renderUiScript(options?: { defaultSessionId?: string }): string {
  return personalize(getClientScript(), { version: "", ...options });
}
